### ISSUE TITLE
Add variables

### ISSUE THREAD

**Issue by nacalai** [bitfocus/companion-module-h2r-graphics#10]
Loving H2R! I would also love to have variables.

The use case would for example be to show lower third names. It would be awesome to just have companion reflect whatever I type into Lower third nr 1,2 etc etc.

**Comment by farm-cyeo** [comment]
I agree... 

I am setting up a process so I can process through 30+ lower thirds...  So I have an internal variable (set to 0 to start), then I have a button to add 1 to the variable, then I want to show the lower third for the variable number.

When I choose "h2r-graphics: Lower Third - Show", I can't tell it to use the variable to pass the number and display that lower third.

**Comment by iamjohnbarker** [comment]
Added in the latest beta!

**Comment by farm-cyeo** [comment]
Awesome. Going to go grab it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
