### ISSUE TITLE
Pass H2R Variable Text/lists to Companion

### ISSUE THREAD

**Issue by iamjohnbarker** [bitfocus/companion-module-h2r-graphics#11]
[textx] and [listx.y] should pass programmed value instead of variable name. Could be used to change button text dynamically such as changing lower third values

**Comment by davidjoshuaford** [comment]
I am looking for this feature as well. 

Actually would like the Social action to bring in the Name text and Comment text, which could then be used to time stamp to a spreadsheet, to create chapter marker log. Post-show, this would make it much faster to identify Q&A markers.
