### ISSUE TITLE
Delayed Actions

### ISSUE THREAD

**Issue by farm-cyeo** [bitfocus/companion-module-h2r-graphics#18]
Hi John,

Thanks for doing all the work to integrate in V2.

I am starting to work on my workflow with the new version, and either I have something wrong, or there is an issue with the delay field.

Here is the workflow I have:

(Delay 0) Show graphic - lower 3rd with data from a list
(Delay 10) Internal - change background colour
(Delay 7000) Hide graphic - lower 3rd after 7 secs
(Delay 7000) Variable list select next row
(Delay 7005) Internal - change background colour

Now on other actions that I have (specifically internal actions), what I would do is have delay 0 for everything except hide graphic...

If I do delay 0 for everything but hide, I will get the wrong data line and the background colour won't work.

So the specific item that I have that I am comparing this to is the following:

(Delay 0) Internal run shell for a mp3 file
(Delay 0) Internal change background colour
(Delay 40000) Internal change background colour

Now in this case the MP3 file is 38 seconds long, so I play it, and change the background to red so I know it's playing.  Then once 40 seconds is done I change it to green indicating that it is complete.  Base background colour is black.

So can you take a quick look at the top workflow and let me know if that makes sense for what I am trying to do, or if there is an issue with the delay.

Thanks!

Chris

**Comment by champagj** [comment]
Hello Chris,
Not sure you found a solution to your problem.
In the Edit Button tab, there is a toggle option for "Relative Delays". If check each timer / action will run sequentially one after the other.
If the option is uncheck (default) all timer start at the same time and actions performed when the timer is reached regardless of the order of the actions.
