### ISSUE TITLE
"Update content - Image" no longer working

### ISSUE THREAD

**Issue by iamjohnbarker** [bitfocus/companion-module-h2r-graphics#19]
Due to a change in H2R Graphics v2.5, images can no longer be updated via companion.

**Comment by krocheck** [comment]
@iamjohnbarker I got so confused by this for a sec.  Got the email notification (I get an email for every issue and every comment in all the repos).  At first I thought you were replying to an OP, then I saw you were the OP so I thought there was a Companion screw up, then I finally realized that it seems you were logging this bug 'for the record'.  LOL.  Correct me if I'm wrong.  🤦‍♂️

**Comment by iamjohnbarker** [comment]
@krocheck It is indeed "for the record". but thanks for checking!

**Comment by alxbouchard** [comment]
HI! Got same problem with Version 2.10.3 (2.10.3) and Companion [2.3.1 (2.3.1+4641-v2-3.1-dc01ac7c)]
The Name update but not the image.
