### ISSUE TITLE
Allow for use of internal Companion variables

### ISSUE THREAD

**Issue by iamjohnbarker** [bitfocus/companion-module-h2r-graphics#20]
As per: 

Related issue: https://github.com/bitfocus/companion/issues/1248

https://github.com/bitfocus/companion-module-obs-studio/pull/135

**Comment by dszoka** [comment]
I came to suggest this…
 would great for using your variables built into h2r graphics… for me… using the zoomiso variables to grab the username from zoom and add it to h2r graphics

**Comment by nugatritter** [comment]
+1
