### ISSUE TITLE
Lower Third Animated -- Update  Content 

### ISSUE THREAD

**Issue by dszoka** [bitfocus/companion-module-h2r-graphics#21]
With the current companion H2R Graphics module your can't update Lower Thirds Animated graphics using the Update Content Feature

**Comment by iamjohnbarker** [comment]
I have accidentally mis-labeled the "Lower Thirds Animated" graphic to "Two lines".

I will update the name in the future, however for now you can use the "Two Lines" option for now and it'll work just fine.
