### ISSUE TITLE
Timers broken again

### ISSUE THREAD

**Issue by pixelauthor** [bitfocus/companion-module-h2r-graphics#23]
Updated to v2.9.1 of H2R Graphics, and was trying to hook my timers back up to Companion. I can trigger timers just fine, but while the "Update content - Time" method seems to update the value of the the time graphic just fine, it's not reflected once the graphic is run. If I set the value manually within H2R Graphics, that time is the only time that ever displays. I have buttons to start different timers (5, 10, 15, 20, etc) but the only time that ever shows up is the 10 minutes I set inside H2R Graphics initially.

UPDATE: I've also noticed that when the window looses focus, the timer in OBS stops updating. The timer continues to count down fine, but OBS doesn't update unless the window is visible or being previewed using ALT+Tab or by hovering over H2R Graphics in the Windows Taskbar.

**Comment by iamjohnbarker** [comment]
RE Timers: Working on a fix for this now - Thanks for reporting.

As for the OBS issue, i'm not sure I can do much with that if OBS is causing the timer to stop - perhaps they want to save resources on the browser sources?
