### ISSUE TITLE
[BUG] H2R Graphic plugin in Companion

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-h2r-graphics#25]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have last version of H2R Graphic: v2.12.3
I created new LIST, so have LIST 1 and LIST 2.
When I try to select source item of list, there is still possible to choice only LIST 1.

### Steps To Reproduce

1. create LIST 2 in H2R Graphic
2. goto companion and try to select item from list 2

### Environment (please complete the following information)

```markdown
- OS: Win7
- Browser: Chrome
- Companion Version: 2.4.1 (2.4.1+4899-09d279c6)
```

**Comment by Suenee** [comment]
I think the easiest way to fix this is to change the selection to input type=number. Currently, it is hard set that only "LIST 1" can be selected. Check out https://github.com/bitfocus/companion-module-h2r-graphics/blob/2809a2147bc18de5f907796576da63da66accb8a/src/actions.js#L916

The processing of the action at https://github.com/bitfocus/companion-module-h2r-graphics/blob/2809a2147bc18de5f907796576da63da66accb8a/src/actions.js#L1368 is then fine.

Of course the ideal solution would be to retrieve from H2R what LISTS are available. I give the above idea as a quick fix. :-)

**Comment by iamjohnbarker** [comment]
Fixing in the next version!
