### ISSUE TITLE
Time - To Time of Day variable showing wrong time.

### ISSUE THREAD

**Issue by iamjohnbarker** [bitfocus/companion-module-h2r-graphics#27]
Appears to be a formatting issue within the display portion the module

**Comment by johnman51** [comment]
Hello!

I had the same issue and I discovered that you always need a NTP (Network Time Protocol) fed into your network (port 123).
For my use, I use Wan internet source at home to get it (it's automatic).
After a 1 or 2 minutes, every devices get the same clock.
And when I'm in a venue, I use Tethering as WAN with a USB cable connected to my Router for a short time at aim to "synchronise" my devices, specially my raspberry which don't have any RTC modules to keep time clock when OFF.

It's a little but useful process when you meet this issue.
I don't know if this is what you need, but this is a good start.

Kind regards, 
John M.
