### ISSUE TITLE
Timer - Custom UP and Timer - Custom DOWN non-functional

### ISSUE THREAD

**Issue by pixelauthor** [bitfocus/companion-module-h2r-graphics#3]
It seems like the custom timers in this module don't work. I can activate and deactivate timers using hide/show, but I have to input the timer values and select the timer type directly in H2RGraphics at this point.

**Comment by josephdadams** [comment]
@iamjohnbarker any input here?

**Comment by iamjohnbarker** [comment]
Fixing coming soonish (it's actually broken in H2R Graphics, as opposed to anything to do with Companion).

I need to release v0.0.8 and i'm gearing up for that!

Thanks for raising it!

**Comment by iamjohnbarker** [comment]
@pixelauthor - Fixed in the latest version of H2R Graphics (0.0.8) which was just released! https://heretorecord.com/graphics#download

**Comment by pixelauthor** [comment]
> @pixelauthor - Fixed in the latest version of H2R Graphics (0.0.8) which was just released! https://heretorecord.com/graphics#download

You rock @iamjohnbarker! Will be using in a live production next week - thanks for the awesome tool!

**Comment by iamjohnbarker** [comment]
No problem @pixelauthor - send me an email with it in action, if you get a chance!

**Comment by iamjohnbarker** [comment]
Can we close this one @josephdadams, or can you give me access to close it?

**Comment by josephdadams** [comment]
Closed and added you as maintainer to the repo.

**Comment by iamjohnbarker** [comment]
Wonderful - thanks @josephdadams!
