### ISSUE TITLE
Feature request : Transition Override in "Show/Hide graphic" action

### ISSUE THREAD

**Issue by kornelion** [bitfocus/companion-module-h2r-graphics#36]
Hi,

Title is pretty much self explanatory : the idea is to have the possibility to use "default" transition or override it with the "fade, fade and slide, etc etc" with a dropdown selector below the "graphic" dropdown selector. It would allow more flexibility. 

Thanks

**Comment by iamjohnbarker** [comment]
Sure thing! I will add this in the next version of the module!
