### ISSUE TITLE
New Big Timer Graphics (countdown, count up, to time of day) not supported by Actions

### ISSUE THREAD

**Issue by champagj** [bitfocus/companion-module-h2r-graphics#39]
Running H2R-Graphics 2.18.2 Beta (PRO version) & Companion 3.2.0+6623

**There are 3 new graphics (Pro version) for Big Timer** 

![image](https://github.com/bitfocus/companion-module-h2r-graphics/assets/47355785/5f30898f-1d88-4108-be4c-2b956efecf28)

**New graphics support run/resume and reset from the H2R interface.**

![image](https://github.com/bitfocus/companion-module-h2r-graphics/assets/47355785/e60a59b4-c628-43aa-9f48-75456f7ecba5)

**Companion has support for Actions Run/Resume, Pause,  Reset, Set Duration,**

![image](https://github.com/bitfocus/companion-module-h2r-graphics/assets/47355785/430c6271-8dd5-4d3c-ad81-2a70a8df9c83)

**But cant be selected / used.**

![image](https://github.com/bitfocus/companion-module-h2r-graphics/assets/47355785/d402d8e0-2b76-4bfb-9674-53c1cc2167f9)

Other functions such as presets, variables appears to work as intended.

**Comment by iamjohnbarker** [comment]
This has since been solved in beta version.
