### ISSUE TITLE
Impossible to send string image for H2R Graphics

### ISSUE THREAD

**Issue by KOHPM** [bitfocus/companion-module-h2r-graphics#5]
Hello, (posted in wrong section)
So far, We were able to use the Companion. thanks.
however the Osc string for H2R image would hide image, whenever it has previously been shown directly from image tab in h2r software.

but if trying to show image from the companion, it won’t work.

Here is the screen shot of the strings
<img width="706" alt="Screen Shot 2020-10-21 at 5 30 51 PM" src="https://user-images.githubusercontent.com/44657017/96800684-e7a04680-13d3-11eb-914f-2fbf191e5c15.png">
Thanks

**Comment by iamjohnbarker** [comment]
I'd like to know more about this. Are you still having trouble? are other OSC strings working?

**Comment by KOHPM** [comment]
> I'd like to know more about this. Are you still having trouble? are other OSC strings working?

Thank you. We have solved it by placing #numbers prior the image title.
