### ISSUE TITLE
Set text variable with a Companion variable

### ISSUE THREAD

**Issue by iamjohnbarker** [bitfocus/companion-module-h2r-graphics#50]
It would be nice to allow users to update a [text.x] variable with any $(companion_variable) - right now it would see that only text is allowed within the "set text variable" input.

<img width="1007" alt="Screenshot 2024-03-14 at 09 47 56" src="https://github.com/bitfocus/companion-module-h2r-graphics/assets/7009061/63de34f3-5b8e-4271-ba26-3b21fd53ba49">

**Comment by kanetreble** [comment]
Second this - this would be amazing to be able to add variables like timestamps ($(atem:record_duration_hms)) into Lists - any assistance greatly appreciated.

**Comment by iamjohnbarker** [comment]
Adding this to the next release!
