### ISSUE TITLE
make custom lable by the Timer & Big Timer graphics visible on Companion button

### ISSUE THREAD

**Issue by Hennyr** [bitfocus/companion-module-h2r-graphics#53]
Dear John,
Is it possible to make the custom lable by the Timer & Big Timer available in Companion. Otherwise the timers all read in Companion as 'Big Timer' or 'Timer'
H2R graphics 2.19, Companion 3.3.0

Big Timer-graphics do not have a seperate namefield, thats why they are all named 'Big Timer' as button-name in Companion. very confusioning

**Comment by iamjohnbarker** [comment]
very true - adding the option to use graphic labels in the next version of the module.

**Comment by Hennyr** [comment]
thanks

---
Met vriendelijke groet,

Henny Ribbink

-------- Oorspronkelijke bericht --------

  		ONDERWERP:
  		Re: [bitfocus/companion-module-h2r-graphics] make custom lable by the 
Timer & Big Timer graphics visible on Companion button (Issue #53)

  		DATUM:
  		02-08-2024 15:51

  		AFZENDER:
  		John Barker ***@***.***>

  		ONTVANGER:
  		bitfocus/companion-module-h2r-graphics 
***@***.***>

very true - adding the option to use graphic labels in the next version 
of the module.

--
Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
You are receiving this because you authored the thread.Message ID: 
***@***.***>

Links:
------
[1] 
https://github.com/bitfocus/companion-module-h2r-graphics/issues/53#issuecomment-2265449143
[2]
