### ISSUE TITLE
Toggle Cue Status

### ISSUE THREAD

**Issue by chrisspiegl** [bitfocus/companion-module-h2r-graphics#55]
The different cue on/off and toggle state buttons are helpful.
I find the "Toggle Cue" option missing.

Since the Feedback already can be set based on Cue On/Off as well as Coming/Going/On Air.

But the “Toggle” option that is currently present in the Companion module instantly toggles the graphic on/off instead of cueing it first.

![image](https://github.com/bitfocus/companion-module-h2r-graphics/assets/1096384/2699378e-ded6-4f2d-b81f-73963b47396e)

**Comment by iamjohnbarker** [comment]
I will add this to the next version however it requires a change in the Module and the H2R Graphics application so stay tuned for an update to both in the coming weeks.
