### ISSUE TITLE
Unavailable when the WAN internet is down or slow

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-h2r-graphics#58]
**Describe the bug**
It has repeatedly happened to me that when I start the computer, the application reports that I do not have a license, which is not true. 

The error is most likely caused by the fact that the application expects available internet immediately after launch. But my computer connects to the internet later or doesn't have internet available right away.

The quality of the Internet connection should not be a limit for the operation of the application.

**Version**
2.20.5

**To Reproduce**
Steps to reproduce the behaviour:

* Disconnect internet
* Run App

**Expected behaviour**
Fully functional because I paid for the license.

**System**
- Companion 3.3.1 (3.3.1+7001-stable-ee7c3daa)
- Win11
- Chrome last

![image](https://github.com/user-attachments/assets/11c79cd1-be8f-4e5c-b30f-4927c25d681d)

My account is service@suenee.cz, so you can verify that I really have a license.

Workaround:
Run the application repeatedly. Usually the error will not show up after 3-4 attempts. (I have slow internet here sometimes.)

**Comment by iamjohnbarker** [comment]
Thanks for reporting this issue - since it is not strictly related to the Companion module, I will close this issue and follow up with you on email.
