### ISSUE TITLE
[BUG] Lower Third Hide not working

### ISSUE THREAD

**Issue by cyruschoi76** [bitfocus/companion-module-h2r-graphics#6]
I found out the action label is miss named as "t" instead of "lowerthirdsHide" and make the action to hide lower third not working. 

https://github.com/bitfocus/companion-module-h2r-graphics/blob/efd2a7b67920bdc5c099cd860ea318eabd79afc3/index.js#L124

Since I don't have the dev chain setup , is that anyone might able to have a quick fix ?

**Comment by josephdadams** [comment]
Fixed in this repo. I’ll ask on slack for it to get updated in the core. You’ll have to then download the latest beta build.
