### ISSUE TITLE
H2R Graphics drawing controls

### ISSUE THREAD

**Issue by ikayM** [bitfocus/companion-module-h2r-graphics#61]
Hi John,

Thank you for the incredible work on H2R Graphics! It’s a fantastic tool that greatly enhances my live production workflow.

I have a feature request regarding the drawing function. Currently, it appears that adjusting colors and brush radius is only possible through the interface. It would be extremely helpful if these adjustments could be controlled via Companion. This feature would allow for more dynamic and efficient control during live events.

Thank you for considering this suggestion, and I look forward to seeing how H2R Graphics continues to evolve!

Best regards,  
Khaled

**Comment by iamjohnbarker** [comment]
Adding this to the next version!
