### ISSUE TITLE
Special characters in value

### ISSUE THREAD

**Issue by MairieSene** [bitfocus/companion-module-h2r-graphics#7]
Hi !
Using companion with the H2RGraphics integration.
Working great !
Except when I want to "send" text to H2R through companion that has special characters in it (like é, è, à, û etc...).

I don't know if it's a problem within H2RGraphics, Companion or this module...

When writing the text directly in H2R it's working great. But when doing through companion (h2r-graphics: Message - Set a custom message) it's not working (replacing special characters with "?").

Thx !

**Comment by iamjohnbarker** [comment]
App is moving to v2 and this is now possible
